--- #YAML:1.0
name:               Spreadsheet-WriteExcelXML
version:            0.12
abstract:           Create an Excel file in XML format.
author:
    - John McNamara (jmcnamara@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:               5.005
resources:
    MailingList:  http://groups.google.com/group/spreadsheet-writeexcel
    repository:   http://github.com/jmcnamara/spreadsheet-writeexcelxml
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
